theme: jekyll-theme-minimal
title: Backtrack to the future
description: remontADA project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Main
    url: main

